config/routes.rb
Rails.application.routes.draw do

  root 'accounts#index'
  resources :accounts do
    resources :records
  end

  resources :records

end

app/models/account.rb
class Account < ActiveRecord::Base

  has_many :records

  def credit
    self.update_attributes!(balance: Record.where('account_id = ?', self.id).sum(:amount))
  end
end

app/models/record.rb
class Record < ActiveRecord::Base

  belongs_to :account

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to account_path(@account)
    else
      render 'new'
    end
  end

  private

  def account_params
    params.require(:account).permit(:description, :balance)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  # before_action :find_account

  def index
    @records = Record.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def new
    @record = Record.new
    @account = Account.find(params[:account_id])
  end

  def create
    @account = Account.find(params[:account_id])
    @record = @account.records.create(record_params)
    @account.credit
    redirect_to account_path(@account)
  end

  private

  def record_params
    params.require(:record).permit(:memo, :amount, :account_id)
  end

  # def find_account
  #   if params[:account_id]
  #     @account = Account.find(params[:account_id])
  #   end
  # end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/index.html.erb
<h1>Accounts</h1>
<table>
  <tr>
    <th>Description</th>
    <th>Total Balance</th>
  </tr>
  <% @accounts.each do |f| %>
    <tr>
      <td><%= link_to f.description, account_path(f) %></td>
      <td><%= f.balance %></td>
    </tr>
  <% end %>
</table>

app/views/accounts/new.html.erb
<h1>Accounts#new</h1>
<p>Find me in app/views/accounts/new.html.erb</p>

app/views/accounts/show.html.erb
<h1><%= @account.description %></h1>
<table>
  <tr>
    <th>Total Balance: </th>
    <td><%= @account.balance %></td>
  </tr>
</table>

<%= link_to "New Record", new_account_record_path(@account) %>

<hr>

<table>
  <tr>
    <th>Record</th>
    <th>Amount</th>
    <th>Created At</th>
  </tr>
  <% @account.records.each do |f| %>
    <tr>
      <td><%= f.memo %></td>
      <td><%= f.amount %></td>
      <td><%= f.created_at.strftime("%I:%M %p %m/%d/%Y") %></td>
    </tr>
  <% end %>
  <tr>
    <th>
      <%= form_for([ @account, @account.records.build], method: :post) do |f| %>
      <%= render(partial: 'records/form', locals: {f: f}) %>
      <%= f.submit("Submit") %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>Total: </th>
    <td><%= @account.balance %></td>
  </tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Financial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/records/_form.html.erb
<table>
  <tr>
    <th><%= f.label(:memo) %></th>
    <td><%= f.text_field(:memo) %></td>
  </tr>
  <tr>
    <th><%= f.label(:amount) %></th>
    <td><%= f.text_field(:amount) %></td>
  </tr>
</table>

app/views/records/index.html.erb
<h1>Records#index</h1>
<p>Find me in app/views/records/index.html.erb</p>

app/views/records/new.html.erb
<%= form_for @record do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit("Submit") %>
<% end %>

app/views/records/show.html.erb
<h1>Records#show</h1>
<p>Find me in app/views/records/show.html.erb</p>